### ISSUE TITLE
Crash on sync

### ISSUE THREAD

**Issue by gael-vanderlee** [ViscousPotential/GitSync#6]
Hello,

I would really like to use this application to sync my obsidian vault but it unfortunately doesn't seem to work on my oneplus 7 pro using Android 12.
When I either:
- Clone remote repository
- Point it to a local folder with a cloned repo
The application just crashes back to home screen, with no error message.
What's weird is that when I check the file system, all the files cloned successfully in the folder, the app crashed afterwards. 
Needless to say synching doesn't work because of this.
Hopefully this can be fixed as I like this app's functionality.

**Comment by ViscousPot** [comment]
Hi,

Thanks for trying my app! Sorry that it hasn't worked as expected though. I've just uploaded a new release that has bug reporting added.
https://github.com/ViscousPotential/GitSync/releases/tag/v1.301

Could you try installing it and trying again. If the same thing happens, check your notification shade for a new notification titled `Application Error Detected`. It may be combined with or separate from the GitSync persistent notification. Clicking on this notification will prompt you to select an email client. On my end, when I select outlook, it auto fills the subject, to line and description. You should just have to press send and I should get a report that should be useful for fixing the underlying issue.

Please ping any questions you have 🙏

**Comment by gael-vanderlee** [comment]
The error reporting worked, I've sent an email. Hopefully this helps you track down the issue

**Comment by ViscousPot** [comment]
Hey I think I have fixed your issue!

Root Cause: Application expected repository main branch to be `master`. User likely had `main` branch when error was encountered.

Fix: https://github.com/ViscousPotential/GitSync/releases/tag/v.1.302

Please can you confirm the fix and I will close the ticket 😄

**Comment by gael-vanderlee** [comment]
Can confirmed it's fixed :) 
Thanks for being so responsive !

**Comment by ViscousPot** [comment]
Thanks for helping make the app better!

**Comment by ViscousPot** [comment]
Hi,

Not sure if you managed to resolve this, but I have released a newer version that is more stable. Please give it a go and let me know if you have any issues

https://github.com/ViscousPotential/GitSync/releases/tag/v1.402


________________________________
From: gael-vanderlee ***@***.***>
Sent: Monday, September 2, 2024 9:46:47 PM
To: ViscousPotential/GitSync ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ViscousPotential/GitSync] Crash on sync (Issue #6)


Hello,

I would really like to use this application to sync my obsidian vault but it unfortunately doesn't seem to work on my oneplus 7 pro using Android 12.
When I either:

  *   Clone remote repository
  *   Point it to a local folder with a cloned repo
The application just crashes back to home screen, with no error message.
What's weird is that when I check the file system, all the files cloned successfully in the folder, the app crashed afterwards.
Needless to say synching doesn't work because of this.
Hopefully this can be fixed as I like this app's functionality.
